import {SITE, CATEGORIES, escape as e, safeUrl, articleBody} from './content.mjs';

export const NAV = [['/','홈'],['/reading/','읽을거리'],['/apt/','아파트 실거래가'],['/lotto/','로또'],['/tools/','유용한 도구'],['/news/','뉴스']];
export function header(active='') {
  return `<div class="modu-header"><a class="modu-skip" href="#main-content">본문으로 건너뛰기</a><div class="modu-header-inner"><a class="modu-wordmark" href="/" aria-label="MODU.TODAY 홈">modu<span>.</span><small>TODAY</small></a><nav class="modu-primary-nav" aria-label="주요 메뉴">${NAV.map(([url,label])=>`<a href="${url}"${active===url?' aria-current="page"':''}>${label}</a>`).join('')}</nav></div></div>`;
}
export function footer() { return `<footer class="modu-footer"><div><a class="modu-wordmark" href="/">modu<span>.</span><small>TODAY</small></a><p>일상에 도움이 되는 읽을거리와 생활 도구.</p></div><nav aria-label="사이트 안내"><a href="/about/">소개</a><a href="/contact/">문의</a><a href="/privacy/">개인정보처리방침</a><a href="/terms/">이용안내</a></nav><small>© MODU.TODAY</small></footer>`; }
export function page({title,description,path,body,noindex=false,article=null,script=''}) {
  const canonical = SITE + path;
  const jsonld = article ? {'@context':'https://schema.org','@type':'BlogPosting',headline:article.title,description:article.description,datePublished:article.publishedAt,dateModified:article.updatedAt,author:{'@type':'Organization',name:'MODU.TODAY',url:SITE+'/about/'},mainEntityOfPage:canonical,...(article.image?{image:SITEimage(article.image)}:{}),publisher:{'@type':'Organization',name:'MODU.TODAY',url:SITE}} : null;
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} | MODU.TODAY</title><meta name="description" content="${e(description)}"><meta name="robots" content="${noindex?'noindex,follow':'index,follow,max-image-preview:large'}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="${article?'article':'website'}"><meta property="og:site_name" content="MODU.TODAY"><meta property="og:locale" content="ko_KR"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${e(article?.image?SITEimage(article.image):SITE+'/assets/og.png')}"><meta name="twitter:card" content="summary_large_image">${article?`<meta property="article:published_time" content="${e(article.publishedAt)}"><meta property="article:modified_time" content="${e(article.updatedAt)}">`:''}<link rel="stylesheet" href="/assets/site.css">${jsonld?`<script type="application/ld+json">${JSON.stringify(jsonld).replace(/</g,'\\u003c')}</script>`:''}</head><body class="editorial-site">${header(path.startsWith('/reading/')?'/reading/':path)}<main id="main-content" class="site-main">${body}</main>${footer()}${script?`<script type="module" src="${script}"></script>`:''}<script defer src="/_vercel/insights/script.js"></script></body></html>`;
}
function SITEimage(value) { const url = safeUrl(value); return url.startsWith('/') ? SITE+url : url; }
const date = value=>e(value?.slice(0,10).replaceAll('-','.'));
const NEWS_CATEGORIES = new Set(['국내 증시 / 코스피 코스닥','환율 및 글로벌 원자재 시세','공모주 청약 및 IPO 일정','정부 지원금 및 정책 소식','미국 증시 / 글로벌 매크로','야간선물 / 파생 / 투자시황']);
export function validNewsItems(news) {
  const items = Array.isArray(news?.items) ? news.items : [];
  return items.filter(item => item && NEWS_CATEGORIES.has(item.category)
    && typeof item.title === 'string' && item.title.trim() && item.title.trim() !== '기사 보기'
    && typeof item.source === 'string' && item.source.trim()
    && typeof item.url === 'string' && item.url.startsWith('https://') && safeUrl(item.url));
}
function cover(post) { return post.image?`<img src="${e(safeUrl(post.image))}" alt="${e(post.imageAlt)}" loading="lazy" referrerpolicy="no-referrer">`:`<div class="cover-text"><span>modu. journal</span><strong>${e(post.category)}</strong><span>일상에서 발견하는 생각</span></div>`; }
export function card(post) { return `<article class="post-card" data-category="${e(post.category)}" data-search="${e([post.title,post.description,...post.tags].join(' ').toLowerCase())}"><a href="/reading/${post.id}/" class="post-cover" tabindex="-1" aria-hidden="true">${cover(post)}</a><div class="post-info"><span class="eyebrow">${e(post.category)}</span><h3><a href="/reading/${post.id}/">${e(post.title)}</a></h3><p>${e(post.description)}</p><span class="meta">${date(post.publishedAt)} · MODU.TODAY</span></div></article>`; }
const empty = `<div class="empty-editorial"><span class="eyebrow">MODU JOURNAL</span><h3>매일의 궁금함을, 하나씩 깊이 있게.</h3><p>생활·IT·자동차·부동산·경제·취미까지.<br>직접 확인하고 정리한 글을 이곳에 차곡차곡 담겠습니다.</p><a class="text-link" href="/about/">MODU.TODAY 소개 →</a></div>`;
function sectionHead(kicker,title,url,label='전체 보기') { return `<div class="section-head"><div><span class="eyebrow">${kicker}</span><h2>${title}</h2></div>${url?`<a class="text-link" href="${url}">${label} <span aria-hidden="true">↗</span></a>`:''}</div>`; }
const toolCards = `<a class="tool-item" href="/calculator/"><span class="tool-symbol">÷</span><div><h3>생활 계산기</h3><p>퍼센트부터 연봉·대출까지</p></div><span>↗</span></a><a class="tool-item" href="/games/"><span class="tool-symbol">▦</span><div><h3>잠깐, 게임 한 판</h3><p>블록·지뢰찾기·2048</p></div><span>↗</span></a><a class="tool-item" href="/youtube/"><span class="tool-symbol">▷</span><div><h3>YouTube 순위</h3><p>조회수 변화로 보는 관심사</p></div><span>↗</span></a>`;
function newsItems(news,limit) {
  return validNewsItems(news).slice(0,limit).map(n=>`<a class="news-item" href="${e(safeUrl(n.url))}" target="_blank" rel="noopener noreferrer nofollow"><span>${e(n.source)} · 외부 기사</span><strong>${e(n.title)}</strong><span aria-hidden="true">↗</span></a>`).join('') || '<p class="muted">현재 표시할 뉴스가 없습니다. 다음 수집 시 갱신됩니다.</p>';
}
export function home(posts,news,lotto) {
  const life = posts.filter(p=>['생활','경제','부동산'].includes(p.category));
  return page({title:'일상을 읽고, 생활을 더 편리하게',description:'생활·IT·자동차·부동산·경제·취미 읽을거리와 아파트 실거래가, 로또 기록, 생활 계산기를 만나는 MODU.TODAY.',path:'/',body:`
  <section class="hero"><div><span class="eyebrow">THE EVERYDAY JOURNAL</span><h1>일상을 읽고,<br>생활을 더 <em>편리하게.</em></h1><p>궁금했던 이야기에는 조금 더 깊이를.<br>매일 필요한 정보에는 조금 더 편리함을.</p><div class="hero-actions"><a class="button" href="/reading/">읽을거리 둘러보기 <span>↗</span></a><a class="text-link" href="/tools/">생활 도구 찾아보기 →</a></div><div class="hero-quicklinks"><a href="/apt/">아파트 실거래가 ↗</a><a href="/lotto/">로또 당첨정보 ↗</a></div></div><aside class="hero-note"><span class="note-index">01 / OUR EVERYDAY</span><p>작은 발견이<br>더 나은 하루를<br>만듭니다<span>.</span></p><div class="topic-line">LIFE · TECH · HOME · MONEY</div></aside></section>
  <section id="latest-reading" class="home-section">${sectionHead('JOURNAL','최신 읽을거리','/reading/')}<div class="post-grid">${posts.length?posts.slice(0,3).map(card).join(''):empty}</div><div class="category-row">${CATEGORIES.map(c=>`<a href="/reading/?category=${encodeURIComponent(c)}">${c}</a>`).join('')}</div></section>
  <section id="everyday-shortcuts" class="home-section">${sectionHead('EVERYDAY ESSENTIALS','자주 찾는 생활 정보')}<div class="essential-grid"><a class="essential apt-feature" href="/apt/"><span class="eyebrow">HOME & LIVING</span><div class="building-art" aria-hidden="true">▥<span>▥</span>▥</div><h2>아파트 실거래가</h2><p>우리 동네, 실제로 얼마에 거래됐을까?<br>지역·단지별 신고 거래를 직접 확인하세요.</p><span class="feature-link">실거래가 검색하기 <b>↗</b></span></a><a class="essential lotto-feature" href="/lotto/"><span class="eyebrow">LOTTO ARCHIVE</span><span class="draw-label">${lotto?.draw?`${e(lotto.draw)}회 · ${date(lotto.date)} 추첨`:'회차별 추첨 기록'}</span><h2>로또 당첨정보</h2><p>당첨번호와 회차별 기록, 당첨지역까지.<br>번호 생성기도 함께 이용하세요.</p><div class="lotto-balls">${(lotto?.numbers||[]).map(n=>`<span>${e(n)}</span>`).join('')}${lotto?.bonus?`<small>+</small><span class="bonus">${e(lotto.bonus)}</span>`:''}</div><span class="feature-link">로또 확인하기 <b>↗</b></span></a></div></section>
  <section id="life-economy" class="home-section">${sectionHead('BETTER EVERYDAY','생활과 경제, 알아두면 좋은 것들','/reading/?category=%EC%83%9D%ED%99%9C')}<div class="${life.length?'post-grid':'guide-grid'}">${life.length?life.slice(0,3).map(card).join(''):`<a class="guide-card" href="/calculator/percent.html"><span class="eyebrow">생활 속 숫자</span><h3>할인율과 증가율,<br>기준부터 확인하기</h3><p>예제와 함께 직접 계산해 보세요.</p><span class="text-link">퍼센트 계산기 →</span></a><a class="guide-card" href="/calculator/area.html"><span class="eyebrow">집을 알아볼 때</span><h3>제곱미터와 평,<br>면적 단위 비교하기</h3><p>숫자를 바꿔 보며 면적을 확인하세요.</p><span class="text-link">면적 계산기 →</span></a><a class="guide-card" href="/calculator/loan.html"><span class="eyebrow">지출 계획</span><h3>상환 방식에 따라<br>매달 부담은 어떻게 달라질까?</h3><p>조건을 입력해 예상 금액을 비교하세요.</p><span class="text-link">대출 계산기 →</span></a>`}</div></section>
  <section id="useful-tools" class="home-section">${sectionHead('SMALL TOOLS, BIG HELP','유용한 도구','/tools/')}<div class="tools-grid">${toolCards}</div></section>
  <section id="latest-news" class="home-section news-section">${sectionHead('AROUND THE WORLD','주요 뉴스','/news/','뉴스 더 보기')}<p class="muted">외부 언론의 제목과 원문 링크입니다. 자체 읽을거리와 구분해 제공합니다.</p><div class="news-list">${newsItems(news,4)}</div><p class="meta">최근 수집: ${e(news.updatedAtLabel || news.updatedAt || '확인 중')}</p></section>`});
}
export function reading(posts) {
  const categories=[...new Set([...CATEGORIES,...posts.map(p=>p.category)])];
  return page({title:'읽을거리',description:'생활, IT, 자동차, 부동산, 경제, 주식, 취미. 일상의 궁금함을 직접 확인하고 정리하는 MODU.TODAY 읽을거리.',path:'/reading/',script:'/assets/reading.js',body:`<div class="page-intro"><span class="eyebrow">MODU JOURNAL</span><h1>읽을거리</h1><p>하나의 주제에 갇히지 않는, 일상의 발견과 기록.</p></div><form class="reading-search" role="search"><label for="reading-query">글 검색</label><input id="reading-query" type="search" placeholder="제목, 내용 요약, 태그 검색"><button type="submit" class="button">검색</button></form><div class="category-row" role="group" aria-label="카테고리"><button type="button" data-filter="" aria-pressed="true">전체</button>${categories.map(c=>`<button type="button" data-filter="${e(c)}" aria-pressed="false">${e(c)}</button>`).join('')}</div><p id="reading-count" class="meta" aria-live="polite">${posts.length}개의 글</p><div class="post-grid">${posts.length?posts.map(card).join(''):empty}</div><p id="no-results" class="empty-editorial" hidden>조건에 맞는 글이 없습니다. 다른 주제나 검색어로 찾아보세요.</p>`});
}
export function article(post) {
  return page({title:post.title,description:post.description,path:`/reading/${post.id}/`,article:post,body:`<article class="article"><a class="text-link" href="/reading/">← 읽을거리 목록</a><header class="article-heading"><span class="eyebrow">${e(post.category)}</span><h1>${e(post.title)}</h1><p>${e(post.description)}</p><div class="meta">MODU.TODAY 편집부 · 작성 <time datetime="${e(post.publishedAt)}">${date(post.publishedAt)}</time> · 수정 <time datetime="${e(post.updatedAt)}">${date(post.updatedAt)}</time></div></header>${articleBody(post)}<div class="category-row">${post.tags.map(t=>`<a href="/reading/?q=${encodeURIComponent(t)}">#${e(t)}</a>`).join('')}</div><aside class="article-end"><p>더 궁금한 점이나 정정할 내용이 있나요?</p><a href="/contact/">문의 및 정정 제보 →</a><a href="/reading/">다른 읽을거리 보기 →</a></aside></article>`});
}
export function newsPage(news) {
  news = {...news, items:validNewsItems(news)};
  const groups=[...new Set(news.items.map(n=>n.category))];
  return page({title:'뉴스 모아보기',description:'주요 경제·정책 뉴스를 출처와 함께 확인하는 외부 기사 링크 모음입니다. 원문은 각 언론사에서 확인하세요.',path:'/news/',noindex:true,body:`<div class="page-intro"><span class="eyebrow">NEWS LINKS</span><h1>뉴스 모아보기</h1><p>세상의 흐름을 살펴보는 보조 자료.<br>제목을 누르면 외부 원문으로 이동합니다.</p><span class="meta">최근 수집: ${e(news.updatedAtLabel || news.updatedAt || '확인 중')}</span></div>${groups.map(g=>`<section class="home-section"><h2>${e(g)}</h2><div class="news-list">${newsItems({items:news.items.filter(n=>n.category===g)},6)}</div></section>`).join('')}<p class="muted">자동 수집된 제목과 출처만 제공합니다. 기사 본문은 복제하지 않으며, 보도 내용과 발행 시점은 원문에서 확인하세요.</p>`});
}
export function toolsPage() {
  return page({title:'유용한 도구',description:'아파트 실거래가, 로또 기록, 생활 계산기, 무료 게임과 YouTube 조회수 비교를 한곳에서 이용하세요.',path:'/tools/',body:`<div class="page-intro"><span class="eyebrow">TOOLS FOR EVERYDAY</span><h1>생활이 조금 더 쉬워지는 도구</h1><p>계산하고, 비교하고, 잠깐 쉬어가세요. 회원가입 없이 바로 이용할 수 있습니다.</p></div><div class="tools-grid">${toolCards}<a class="tool-item" href="/apt/"><span class="tool-symbol">⌂</span><div><h2>아파트 실거래가</h2><p>지역·단지별 신고 거래 검색</p></div><span>↗</span></a><a class="tool-item" href="/lotto/"><span class="tool-symbol">6</span><div><h2>로또</h2><p>당첨번호·당첨지역·번호 생성</p></div><span>↗</span></a></div><section class="home-section"><h2>바로 계산하기</h2><div class="guide-grid">${[['percent','퍼센트'],['salary','연봉 실수령액'],['loan','대출'],['area','면적'],['average-price','주식 평단가'],['car-tax','자동차세']].map(([slug,label])=>`<a class="guide-card" href="/calculator/${slug}.html"><h3>${label}</h3><span>계산기 열기 →</span></a>`).join('')}</div></section>`});
}
